/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.dao.physicalisolation;

import java.util.List;

import com.pamirs.tro.entity.domain.entity.MqDeleteDTO;
import com.pamirs.tro.entity.domain.entity.MqIsolateConfig;
import org.apache.ibatis.annotations.Param;

public interface TMqIsolateConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int insert(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int insertSelective(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    MqIsolateConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int queryConfigExsit(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    List<MqIsolateConfig> queryMqIsolateConfigs(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    List<MqIsolateConfig> queryMqIsolateConfig(@Param("ids") List<Long> ids);

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    List<MqIsolateConfig> queryAllActiveMqIsolateConfig();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    int deleteMqIsolateConfig(MqDeleteDTO dto);
}
