/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.domain.entity;

import java.util.Date;

public class DsModelWithBLOBs extends DsModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_ds_manage.CONFIG
     *
     * @mbggenerated
     */
    private String config;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_ds_manage.PARSE_CONFIG
     *
     * @mbggenerated
     */
    private String parseConfig;


    private Long customerId;

    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_ds_manage
     *
     * @mbggenerated
     */
    public DsModelWithBLOBs(Long id, Long applicationId, String applicationName, Byte dbType, Byte dsType, String url, Byte status,
                            Date createTime, Date updateTime, Byte isDeleted, String config, String parseConfig, Long customerId, Long userId) {
        super(id, applicationId, applicationName, dbType, dsType, url, status, createTime, updateTime, isDeleted);
        this.config = config;
        this.parseConfig = parseConfig;
        this.customerId = customerId;
        this.userId = userId;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_ds_manage
     *
     * @mbggenerated
     */
    public DsModelWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_ds_manage.CONFIG
     *
     * @return the value of t_application_ds_manage.CONFIG
     * @mbggenerated
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_ds_manage.CONFIG
     *
     * @param config the value for t_application_ds_manage.CONFIG
     * @mbggenerated
     */
    public void setConfig(String config) {
        this.config = config == null ? null : config.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_ds_manage.PARSE_CONFIG
     *
     * @return the value of t_application_ds_manage.PARSE_CONFIG
     * @mbggenerated
     */
    public String getParseConfig() {
        return parseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_ds_manage.PARSE_CONFIG
     *
     * @param parseConfig the value for t_application_ds_manage.PARSE_CONFIG
     * @mbggenerated
     */
    public void setParseConfig(String parseConfig) {
        this.parseConfig = parseConfig == null ? null : parseConfig.trim();
    }
}
