/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.domain.entity;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.pamirs.tro.common.util.DateToStringFormatSerialize;
import org.springframework.format.annotation.DateTimeFormat;

public class MqIsolateConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.CLUSTER_NAME
     *
     * @mbggenerated
     */
    private String clusterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.CLUSTER_ALIAS
     *
     * @mbggenerated
     */
    private String clusterAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.NAMESRV_ADDR
     *
     * @mbggenerated
     */
    private String namesrvAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.PT_NAMESRV_ADDR
     *
     * @mbggenerated
     */
    private String ptNamesrvAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.BROKER_NAME
     *
     * @mbggenerated
     */
    private String brokerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.TOPIC
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.CONSUMER_GROUP
     *
     * @mbggenerated
     */
    private String consumerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.ISOLATED_STATUS
     *
     * @mbggenerated
     */
    private Integer isolatedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.BROKER_PROPERTY
     *
     * @mbggenerated
     */
    private String brokerProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.ACTIVE
     *
     * @mbggenerated
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.CREATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = DateToStringFormatSerialize.class)
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.UPDATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = DateToStringFormatSerialize.class)
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mq_isolate_config.FAILED_DETAIL
     *
     * @mbggenerated
     */
    private String failedDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    public MqIsolateConfig(Long id, String clusterName, String clusterAlias, String namesrvAddr, String ptNamesrvAddr,
        String brokerName, String topic, String consumerGroup, Integer isolatedStatus, String brokerProperty,
        String active, Date createTime, Date updateTime, String failedDetail) {
        this.id = id;
        this.clusterName = clusterName;
        this.clusterAlias = clusterAlias;
        this.namesrvAddr = namesrvAddr;
        this.ptNamesrvAddr = ptNamesrvAddr;
        this.brokerName = brokerName;
        this.topic = topic;
        this.consumerGroup = consumerGroup;
        this.isolatedStatus = isolatedStatus;
        this.brokerProperty = brokerProperty;
        this.active = active;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.failedDetail = failedDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbggenerated
     */
    public MqIsolateConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.ID
     *
     * @return the value of t_mq_isolate_config.ID
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.ID
     *
     * @param id the value for t_mq_isolate_config.ID
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.CLUSTER_NAME
     *
     * @return the value of t_mq_isolate_config.CLUSTER_NAME
     * @mbggenerated
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.CLUSTER_NAME
     *
     * @param clusterName the value for t_mq_isolate_config.CLUSTER_NAME
     * @mbggenerated
     */
    public void setClusterName(String clusterName) {
        this.clusterName = clusterName == null ? null : clusterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.CLUSTER_ALIAS
     *
     * @return the value of t_mq_isolate_config.CLUSTER_ALIAS
     * @mbggenerated
     */
    public String getClusterAlias() {
        return clusterAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.CLUSTER_ALIAS
     *
     * @param clusterAlias the value for t_mq_isolate_config.CLUSTER_ALIAS
     * @mbggenerated
     */
    public void setClusterAlias(String clusterAlias) {
        this.clusterAlias = clusterAlias == null ? null : clusterAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.NAMESRV_ADDR
     *
     * @return the value of t_mq_isolate_config.NAMESRV_ADDR
     * @mbggenerated
     */
    public String getNamesrvAddr() {
        return namesrvAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.NAMESRV_ADDR
     *
     * @param namesrvAddr the value for t_mq_isolate_config.NAMESRV_ADDR
     * @mbggenerated
     */
    public void setNamesrvAddr(String namesrvAddr) {
        this.namesrvAddr = namesrvAddr == null ? null : namesrvAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.PT_NAMESRV_ADDR
     *
     * @return the value of t_mq_isolate_config.PT_NAMESRV_ADDR
     * @mbggenerated
     */
    public String getPtNamesrvAddr() {
        return ptNamesrvAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.PT_NAMESRV_ADDR
     *
     * @param ptNamesrvAddr the value for t_mq_isolate_config.PT_NAMESRV_ADDR
     * @mbggenerated
     */
    public void setPtNamesrvAddr(String ptNamesrvAddr) {
        this.ptNamesrvAddr = ptNamesrvAddr == null ? null : ptNamesrvAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.BROKER_NAME
     *
     * @return the value of t_mq_isolate_config.BROKER_NAME
     * @mbggenerated
     */
    public String getBrokerName() {
        return brokerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.BROKER_NAME
     *
     * @param brokerName the value for t_mq_isolate_config.BROKER_NAME
     * @mbggenerated
     */
    public void setBrokerName(String brokerName) {
        this.brokerName = brokerName == null ? null : brokerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.TOPIC
     *
     * @return the value of t_mq_isolate_config.TOPIC
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.TOPIC
     *
     * @param topic the value for t_mq_isolate_config.TOPIC
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.CONSUMER_GROUP
     *
     * @return the value of t_mq_isolate_config.CONSUMER_GROUP
     * @mbggenerated
     */
    public String getConsumerGroup() {
        return consumerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.CONSUMER_GROUP
     *
     * @param consumerGroup the value for t_mq_isolate_config.CONSUMER_GROUP
     * @mbggenerated
     */
    public void setConsumerGroup(String consumerGroup) {
        this.consumerGroup = consumerGroup == null ? null : consumerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.ISOLATED_STATUS
     *
     * @return the value of t_mq_isolate_config.ISOLATED_STATUS
     * @mbggenerated
     */
    public Integer getIsolatedStatus() {
        return isolatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.ISOLATED_STATUS
     *
     * @param isolatedStatus the value for t_mq_isolate_config.ISOLATED_STATUS
     * @mbggenerated
     */
    public void setIsolatedStatus(Integer isolatedStatus) {
        this.isolatedStatus = isolatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.BROKER_PROPERTY
     *
     * @return the value of t_mq_isolate_config.BROKER_PROPERTY
     * @mbggenerated
     */
    public String getBrokerProperty() {
        return brokerProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.BROKER_PROPERTY
     *
     * @param brokerProperty the value for t_mq_isolate_config.BROKER_PROPERTY
     * @mbggenerated
     */
    public void setBrokerProperty(String brokerProperty) {
        this.brokerProperty = brokerProperty == null ? null : brokerProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.ACTIVE
     *
     * @return the value of t_mq_isolate_config.ACTIVE
     * @mbggenerated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.ACTIVE
     *
     * @param active the value for t_mq_isolate_config.ACTIVE
     * @mbggenerated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.CREATE_TIME
     *
     * @return the value of t_mq_isolate_config.CREATE_TIME
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.CREATE_TIME
     *
     * @param createTime the value for t_mq_isolate_config.CREATE_TIME
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.UPDATE_TIME
     *
     * @return the value of t_mq_isolate_config.UPDATE_TIME
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.UPDATE_TIME
     *
     * @param updateTime the value for t_mq_isolate_config.UPDATE_TIME
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mq_isolate_config.FAILED_DETAIL
     *
     * @return the value of t_mq_isolate_config.FAILED_DETAIL
     * @mbggenerated
     */
    public String getFailedDetail() {
        return failedDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mq_isolate_config.FAILED_DETAIL
     *
     * @param failedDetail the value for t_mq_isolate_config.FAILED_DETAIL
     * @mbggenerated
     */
    public void setFailedDetail(String failedDetail) {
        this.failedDetail = failedDetail == null ? null : failedDetail.trim();
    }
}
