/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.domain.entity;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.pamirs.tro.common.util.DateToStringFormatSerialize;
import org.springframework.format.annotation.DateTimeFormat;

public class TApplicationInfoUpload {
    /**
     * 主键id
     */
    private Long taiuId;

    /**
     * 应用名称
     */
    private String applicationName;

    /**
     * 信息类型  1 堆栈 2 SQL 异常
     */
    private Integer infoType;

    /**
     * 上传的信息
     */
    private String uploadInfo;

    /**
     * 创建时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = DateToStringFormatSerialize.class)
    private Date createTime;

    /**
     * 全参数构造函数
     *
     * @param taiuId
     * @param applicationName
     * @param infoType
     * @param uploadInfo
     * @param createTime
     */
    public TApplicationInfoUpload(Long taiuId, String applicationName, Integer infoType, String uploadInfo,
        Date createTime) {
        this.taiuId = taiuId;
        this.applicationName = applicationName;
        this.infoType = infoType;
        this.uploadInfo = uploadInfo;
        this.createTime = createTime;
    }

    /**
     * 无参数构造函数
     */
    public TApplicationInfoUpload() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_info_upload.TAIU_ID
     *
     * @return the value of t_application_info_upload.TAIU_ID
     * @mbggenerated
     */
    public Long getTaiuId() {
        return taiuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_info_upload.TAIU_ID
     *
     * @param taiuId the value for t_application_info_upload.TAIU_ID
     * @mbggenerated
     */
    public void setTaiuId(Long taiuId) {
        this.taiuId = taiuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_info_upload.APPLICATION_NAME
     *
     * @return the value of t_application_info_upload.APPLICATION_NAME
     * @mbggenerated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_info_upload.APPLICATION_NAME
     *
     * @param applicationName the value for t_application_info_upload.APPLICATION_NAME
     * @mbggenerated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_info_upload.INFO_TYPE
     *
     * @return the value of t_application_info_upload.INFO_TYPE
     * @mbggenerated
     */
    public Integer getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_info_upload.INFO_TYPE
     *
     * @param infoType the value for t_application_info_upload.INFO_TYPE
     * @mbggenerated
     */
    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_info_upload.UPLOAD_INFO
     *
     * @return the value of t_application_info_upload.UPLOAD_INFO
     * @mbggenerated
     */
    public String getUploadInfo() {
        return uploadInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_info_upload.UPLOAD_INFO
     *
     * @param uploadInfo the value for t_application_info_upload.UPLOAD_INFO
     * @mbggenerated
     */
    public void setUploadInfo(String uploadInfo) {
        this.uploadInfo = uploadInfo == null ? null : uploadInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_info_upload.CREATE_TIME
     *
     * @return the value of t_application_info_upload.CREATE_TIME
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_info_upload.CREATE_TIME
     *
     * @param createTime the value for t_application_info_upload.CREATE_TIME
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
