/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.dao.dict;

import java.util.List;
import java.util.Map;

import com.pamirs.tro.entity.domain.entity.TDictionaryData;
import com.pamirs.tro.entity.domain.vo.TDictionaryVo;
import org.apache.ibatis.annotations.Param;

public interface TDictionaryDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_data
     *
     * @mbggenerated
     */
    int insert(TDictionaryData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_data
     *
     * @mbggenerated
     */
    int insertSelective(TDictionaryData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_data
     *
     * @mbggenerated
     */
    TDictionaryData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TDictionaryData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TDictionaryData record);

    /**
     * 更新数据字典
     *
     * @param tDictionaryVo
     */
    void updateDictionary(TDictionaryVo tDictionaryVo);

    /**
     * 查询数据字典列表
     *
     * @param paramMap
     * @return
     */
    List<TDictionaryVo> queryDictionaryList(Map<String, Object> paramMap);

    /**
     * 查询数据字典详情
     *
     * @param tDictionaryId
     * @return
     */
    TDictionaryVo queryDictionaryDetail(@Param("tDictionaryId") String tDictionaryId);

    /**
     * 删除数据字典
     *
     * @param tDictionaryIds
     */
    void deleteDictionary(@Param("tDictionaryIds") List<String> tDictionaryIds);

    /**
     * 删除数据字典类型，当有数据字典类型，但没有字典值时，删除
     */
    void deleteEmptyDictType();

}
