/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.dao.bottleneck;

import com.pamirs.tro.entity.domain.entity.LinkBottleneck;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TLinkBottleneckDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    int insert(LinkBottleneck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    int insertSelective(LinkBottleneck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    LinkBottleneck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LinkBottleneck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(LinkBottleneck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LinkBottleneck record);
}
