/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.domain.entity;

import java.util.Date;

public class TDictionaryType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.TYPE_NAME
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.ACTIVE
     *
     * @mbggenerated
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.CREATE_USER_CODE
     *
     * @mbggenerated
     */
    private String createUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.MODIFY_USER_CODE
     *
     * @mbggenerated
     */
    private String modifyUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.PARENT_CODE
     *
     * @mbggenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.TYPE_ALIAS
     *
     * @mbggenerated
     */
    private String typeAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_type.IS_LEAF
     *
     * @mbggenerated
     */
    private String isLeaf;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_type
     *
     * @mbggenerated
     */
    public TDictionaryType(String id, String typeName, String active, Date createTime, Date modifyTime,
        String createUserCode, String modifyUserCode, String parentCode, String typeAlias, String isLeaf) {
        this.id = id;
        this.typeName = typeName;
        this.active = active;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.createUserCode = createUserCode;
        this.modifyUserCode = modifyUserCode;
        this.parentCode = parentCode;
        this.typeAlias = typeAlias;
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_type
     *
     * @mbggenerated
     */
    public TDictionaryType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.ID
     *
     * @return the value of t_dictionary_type.ID
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.ID
     *
     * @param id the value for t_dictionary_type.ID
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.TYPE_NAME
     *
     * @return the value of t_dictionary_type.TYPE_NAME
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.TYPE_NAME
     *
     * @param typeName the value for t_dictionary_type.TYPE_NAME
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.ACTIVE
     *
     * @return the value of t_dictionary_type.ACTIVE
     * @mbggenerated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.ACTIVE
     *
     * @param active the value for t_dictionary_type.ACTIVE
     * @mbggenerated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.CREATE_TIME
     *
     * @return the value of t_dictionary_type.CREATE_TIME
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.CREATE_TIME
     *
     * @param createTime the value for t_dictionary_type.CREATE_TIME
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.MODIFY_TIME
     *
     * @return the value of t_dictionary_type.MODIFY_TIME
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.MODIFY_TIME
     *
     * @param modifyTime the value for t_dictionary_type.MODIFY_TIME
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.CREATE_USER_CODE
     *
     * @return the value of t_dictionary_type.CREATE_USER_CODE
     * @mbggenerated
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.CREATE_USER_CODE
     *
     * @param createUserCode the value for t_dictionary_type.CREATE_USER_CODE
     * @mbggenerated
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode == null ? null : createUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.MODIFY_USER_CODE
     *
     * @return the value of t_dictionary_type.MODIFY_USER_CODE
     * @mbggenerated
     */
    public String getModifyUserCode() {
        return modifyUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.MODIFY_USER_CODE
     *
     * @param modifyUserCode the value for t_dictionary_type.MODIFY_USER_CODE
     * @mbggenerated
     */
    public void setModifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode == null ? null : modifyUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.PARENT_CODE
     *
     * @return the value of t_dictionary_type.PARENT_CODE
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.PARENT_CODE
     *
     * @param parentCode the value for t_dictionary_type.PARENT_CODE
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.TYPE_ALIAS
     *
     * @return the value of t_dictionary_type.TYPE_ALIAS
     * @mbggenerated
     */
    public String getTypeAlias() {
        return typeAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.TYPE_ALIAS
     *
     * @param typeAlias the value for t_dictionary_type.TYPE_ALIAS
     * @mbggenerated
     */
    public void setTypeAlias(String typeAlias) {
        this.typeAlias = typeAlias == null ? null : typeAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_type.IS_LEAF
     *
     * @return the value of t_dictionary_type.IS_LEAF
     * @mbggenerated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_type.IS_LEAF
     *
     * @param isLeaf the value for t_dictionary_type.IS_LEAF
     * @mbggenerated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }
}
