/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.domain.entity;

public class TPressureTimeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.RECORD_ID
     *
     * @mbggenerated
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.START_TIME
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.END_TIME
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbggenerated
     */
    public TPressureTimeRecord(String recordId, String startTime, String endTime) {
        this.recordId = recordId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbggenerated
     */
    public TPressureTimeRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.RECORD_ID
     *
     * @return the value of t_pressure_time_record.RECORD_ID
     * @mbggenerated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.RECORD_ID
     *
     * @param recordId the value for t_pressure_time_record.RECORD_ID
     * @mbggenerated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.START_TIME
     *
     * @return the value of t_pressure_time_record.START_TIME
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.START_TIME
     *
     * @param startTime the value for t_pressure_time_record.START_TIME
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.END_TIME
     *
     * @return the value of t_pressure_time_record.END_TIME
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.END_TIME
     *
     * @param endTime the value for t_pressure_time_record.END_TIME
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}
