/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.domain.entity;

import java.util.Date;

public class TReturnData {
    /**
     * 主键
     */
    private Long trdId;

    /**
     * jar包名称
     */
    private String incDataJarName;

    /**
     * jar包存放路径
     */
    private String incDataJarPath;

    /**
     * 负责人工号
     */
    private String principalNo;

    /**
     * 链路id
     */
    private Long linkId;

    /**
     * 启动类
     */
    private String startClass;

    /**
     * 运行状态 1 运行中 2 已停止
     */
    private Integer loadStatus;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * 全参数构造器
     *
     * @param trdId
     * @param incDataJarName
     * @param incDataJarPath
     * @param principalNo
     * @param linkId
     * @param startClass
     * @param loadStatus
     * @param createTime
     * @param updateTime
     */
    public TReturnData(Long trdId, String incDataJarName, String incDataJarPath, String principalNo, Long linkId,
        String startClass, Integer loadStatus, Date createTime, Date updateTime) {
        this.trdId = trdId;
        this.incDataJarName = incDataJarName;
        this.incDataJarPath = incDataJarPath;
        this.principalNo = principalNo;
        this.linkId = linkId;
        this.startClass = startClass;
        this.loadStatus = loadStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbggenerated
     */
    public TReturnData() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.TRD_ID
     *
     * @return the value of t_return_data.TRD_ID
     * @mbggenerated
     */
    public Long getTrdId() {
        return trdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.TRD_ID
     *
     * @param trdId the value for t_return_data.TRD_ID
     * @mbggenerated
     */
    public void setTrdId(Long trdId) {
        this.trdId = trdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.INC_DATA_JAR_NAME
     *
     * @return the value of t_return_data.INC_DATA_JAR_NAME
     * @mbggenerated
     */
    public String getIncDataJarName() {
        return incDataJarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.INC_DATA_JAR_NAME
     *
     * @param incDataJarName the value for t_return_data.INC_DATA_JAR_NAME
     * @mbggenerated
     */
    public void setIncDataJarName(String incDataJarName) {
        this.incDataJarName = incDataJarName == null ? null : incDataJarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.INC_DATA_JAR_PATH
     *
     * @return the value of t_return_data.INC_DATA_JAR_PATH
     * @mbggenerated
     */
    public String getIncDataJarPath() {
        return incDataJarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.INC_DATA_JAR_PATH
     *
     * @param incDataJarPath the value for t_return_data.INC_DATA_JAR_PATH
     * @mbggenerated
     */
    public void setIncDataJarPath(String incDataJarPath) {
        this.incDataJarPath = incDataJarPath == null ? null : incDataJarPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.PRINCIPAL_NO
     *
     * @return the value of t_return_data.PRINCIPAL_NO
     * @mbggenerated
     */
    public String getPrincipalNo() {
        return principalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.PRINCIPAL_NO
     *
     * @param principalNo the value for t_return_data.PRINCIPAL_NO
     * @mbggenerated
     */
    public void setPrincipalNo(String principalNo) {
        this.principalNo = principalNo == null ? null : principalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.LINK_ID
     *
     * @return the value of t_return_data.LINK_ID
     * @mbggenerated
     */
    public Long getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.LINK_ID
     *
     * @param linkId the value for t_return_data.LINK_ID
     * @mbggenerated
     */
    public void setLinkId(Long linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.START_CLASS
     *
     * @return the value of t_return_data.START_CLASS
     * @mbggenerated
     */
    public String getStartClass() {
        return startClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.START_CLASS
     *
     * @param startClass the value for t_return_data.START_CLASS
     * @mbggenerated
     */
    public void setStartClass(String startClass) {
        this.startClass = startClass == null ? null : startClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.LOAD_STATUS
     *
     * @return the value of t_return_data.LOAD_STATUS
     * @mbggenerated
     */
    public Integer getLoadStatus() {
        return loadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.LOAD_STATUS
     *
     * @param loadStatus the value for t_return_data.LOAD_STATUS
     * @mbggenerated
     */
    public void setLoadStatus(Integer loadStatus) {
        this.loadStatus = loadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.CREATE_TIME
     *
     * @return the value of t_return_data.CREATE_TIME
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.CREATE_TIME
     *
     * @param createTime the value for t_return_data.CREATE_TIME
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return_data.UPDATE_TIME
     *
     * @return the value of t_return_data.UPDATE_TIME
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return_data.UPDATE_TIME
     *
     * @param updateTime the value for t_return_data.UPDATE_TIME
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
