/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.dao.confcenter;

import java.util.List;

import com.pamirs.tro.entity.domain.entity.TUploadInterfaceData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TUploadInterfaceDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbggenerated
     */
    int insert(TUploadInterfaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbggenerated
     */
    int insertSelective(TUploadInterfaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbggenerated
     */
    TUploadInterfaceData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUploadInterfaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUploadInterfaceData record);

    /**
     * 批量插入
     *
     * @param recordList
     * @return
     */
    int insertList(@Param("list") List<TUploadInterfaceData> recordList);

    /**
     * 通过 appname 批量删除
     *
     * @param appName
     * @return
     */
    int deleteByAppName(@Param("appName") String appName);
}
