/*
 * Copyright 2021 Shulie Technology, Co.Ltd
 * Email: shulie@shulie.io
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pamirs.tro.entity.dao.transparentflow;

import com.pamirs.tro.entity.domain.entity.TPressureTimeRecord;
import org.apache.ibatis.annotations.Param;

public interface TPressureTimeRecordDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbggenerated
     */
    int insert(@Param("startTime") String startTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(@Param("recordId") String recordId,
        @Param("endTime") String endTime);

    /**
     * 查询最大的开始压测时间
     *
     * @return
     */
    TPressureTimeRecord queryLatestPressureTime();

}
